config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'main#index'

  resource :cart, only: %i[destroy show] do
    resources :items, only: %i[destroy create]
  end

  resources :product, only: [:show]
  resources :category, only: [:show]
  resources :search, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :profile, only: [:index]
      resources :products, only: [:index]

    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord

  belongs_to :user
end

app/models/brand.rb
# frozen_string_literal:true

class Brand < ApplicationRecord
  include ImageUploader::Attachment(:image)
  
  validates :title, presence: true
  validates :description, presence: true

end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  belongs_to :user

  validates :user_id, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :product
  belongs_to :cart

  validates :cart_id, :quantity, presence: true
end

app/models/category.rb
class Category < ApplicationRecord

	has_ancestry

  has_many :products
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  
  include ImageUploader::Attachment(:image)

  belongs_to :product
end

app/models/product.rb
# frozen_string_literal:true

class Product < ApplicationRecord
  
  include ImageUploader::Attachment(:image)

  has_many :related_products
  has_many :related, through: :related_products
  has_many :galleries
  belongs_to :category

  enum hit: { hit: 1, not_hit: 0 }
  enum status: { active: 1, not_active: 0 }
  scope :active, lambda { where(status: 1) }

  validates :title, presence: true
  validates :price, presence: true
end

app/models/related_product.rb
class RelatedProduct < ApplicationRecord
  belongs_to :product
  belongs_to :related, class_name: 'Product'
end

app/models/user.rb
class User < ApplicationRecord

  include UserOath
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_one :cart, dependent: :destroy
  has_many :authorizations
  
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/api/v1/products_controller.rb
class Api:: V1::ProductsController < Api::V1::BaseController

  skip_before_action :doorkeeper_authorize!, on: :index

  def index
    @products = Product.all.limit(5)
    respond_with @products
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  layout false

  def show

  end

  def destroy
    current_cart.destroy
    render :show
  end
end

app/controllers/main_controller.rb
# frozen_string_literal:true

class MainController < ApplicationController

  before_action :set_page_options

  def index
    @brands = Brand.limit(3)
    @hits = Product.all.limit(8)
  end

  def set_page_options
    @page_title = 'Watches Shop'
    @page_description = 'Watches'
    @page_keywords = 'Man Woman Kids'
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  after_action :register_visit, only: [:show]

  def show
    @product = Product.find(params[:id])
    @categories = Category.all
    @brands = Brand.all
    set_page_options
  end

  attr_accessor :product
  helper_method :recent_products

  def recent_products
    [] if recently.none?
    Product.where(id: recently)
  end

  def recently
    session[:viewed_products] ||= []
  end

  def register_visit
    session[:viewed_products] ||= []
    session[:viewed_products] = ([@product.id] + session[:viewed_products].uniq.take(3))

  end

  def set_page_options
    set_meta_tags product.slice(:title, :keywords, :description)
    add_breadcrumb 'Home', :root_path, title: 'Home'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def products
    @products ||= cart_items.joins(:product).all
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/product/show.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="breadcrumbs-main">
      <ol class="breadcrumb">
        <li><a href="/"><%= render_breadcrumbs %></a></li>
        <li class="active"><%= @product.title %></li>
      </ol>
    </div>
  </div>
</div>

<div class="single contact">
  <div class="container">
    <div class="single-main">
      <div class="col-md-9 single-main-left">
        <div class="sngl-top">
          <div class="col-md-5 single-top-left">
            <% unless @product.galleries == [] %>
              <div class="flexslider">
                <ul class="slides">
                
                  <% @product.galleries.each do |item| %>
                    <li data-thumb="<%= item.image_url %>">
                      <div class="thumb-image">
                        <%= image_tag(item.image_url, alt: "", :data => { :imagezoom => "true" }, class: 'img-responsive zoom-img') if item.image_url %>
                      </div>
                    </li>
                  <% end %>
                </ul>
              </div>
            <% else %>
              <div class="flexslider">
              <ul class="slides">
                <li data-thumb="<%= item.image_url%>">
                  <div class="thumb-image">
                    <%= image_tag(item.image_url, alt: "", :data => { :imagezoom => "true" }, class: "img-responsive") if item.image_url %>
                  </div>
                </li>     
              </ul>
            </div>
            <% end %>
          </div>

          <div class="col-md-7 single-top-right">
            <div class="single-para simpleCart_shelfItem">
              <h2><%= @product.title %></h2>
              <div class="star-on">
                <ul class="star-footer">
                  <li><a href="#"><i></i></a></li>
                  <li><a href="#"><i></i></a></li>
                  <li><a href="#"><i></i></a></li>
                  <li><a href="#"><i></i></a></li>
                  <li><a href="#"><i></i></a></li>
                </ul>
                <div class="review">
                  <a href="#"> 1 custom review</a>
                </div>
                <div class="clearfix"></div>
              </div>
              <h5 class="item-price">$ <%= @product.price %> </h5>
              <% if @product.old_price %>
                <del><%= @product.old_price %></del>
              <% end %>
              <p><%= @product.bytitle %></p>
              <div class="available">
                <ul>
                  <li>Color
                    <select>
                      <option>Silver</option>
                      <option>Black</option>
                      <option>Dark Black</option>
                      <option>Red</option>
                    </select>
                  </li>
                  <li class="size-in">Size
                    <select>
                      <option>Large</option>
                      <option>Medium</option>
                      <option>small</option>
                      <option>Large</option>
                      <option>small</option>
                    </select>
                  </li>
                  <div class="clearfix"></div>
                </ul>
              </div>
              <ul class="tag-men">
                <li><span>Category</span>
                <strong>: <a href="/category/<%= @product.category.id %>" style="...">
                  <%= @product.category.title %></a>
                </strong>
                </li>
              </ul>
              <div class="quantity">
                <input type="number" size="4" value="1" name="quantity" min="1" step="1">
              </div>

              <%=
                link_to 'ADD TO CART',
                        cart_items_path,
                        remote: true,
                        data: { method: :post, id: @product.id },
                        class: "add-cart item_add add-to-cart-link",
                        id: "productAdd"
              %>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>

        <div class="tabs">
          <ul class="menu_drop">
            <li class="item1"><a href="#"><img src="<%= asset_path 'arrow.png' %>" alt="">Description</a>
              <ul>
                <li class="subitem1"><a href="#"><%= @product.description %></a></li>
              </ul>
            </li>

            <li class="item2"><a href="#"><img src="<%= asset_path 'arrow.png' %>" alt="">Information</a>
              <ul>
                <li class="subitem2"><a href="#"><%= @product.content %></a></li>
              </ul>
            </li>

            <li class="item3"><a href="#"><img src="<%= asset_path 'arrow.png' %>" alt="">Reviews</a>
              <ul>
                <li class="subitem1"><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur dignissimos ipsa iusto labore laudantium magni obcaecati quia quidem quis, repudiandae similique soluta velit. Debitis explicabo, fugiat molestias nulla tempore unde.</a></li>
                <li class="subitem2"><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur dignissimos ipsa iusto labore laudantium magni obcaecati quia quidem quis, repudiandae similique soluta velit. Debitis explicabo, fugiat molestias nulla tempore unde.</a></li>
                <li class="subitem3"><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur dignissimos ipsa iusto labore laudantium magni obcaecati quia quidem quis, repudiandae similique soluta velit. Debitis explicabo, fugiat molestias nulla tempore unde.</a></li>
              </ul>
            </li>

            <li class="item4"><a href="#"><img src="<%= asset_path 'arrow.png' %>" alt="">Links</a>
              <ul>
                <li class="subitem2"><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur dignissimos ipsa iusto labore laudantium magni obcaecati quia quidem quis, repudiandae similique soluta velit. Debitis explicabo, fugiat molestias nulla tempore unde.</a></li>
                <li class="subitem3"><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur dignissimos ipsa iusto labore laudantium magni obcaecati quia quidem quis, repudiandae similique soluta velit. Debitis explicabo, fugiat molestias nulla tempore unde.</a></li>
              </ul>
            </li>

            <li class="item5"><a href="#"><img src="<%= asset_path 'arrow.png' %>" alt="">Make a Gift</a>
              <ul>
                <li class="subitem1"><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur dignissimos ipsa iusto labore laudantium magni obcaecati quia quidem quis, repudiandae similique soluta velit. Debitis explicabo, fugiat molestias nulla tempore unde.</a></li>
                <li class="subitem2"><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur dignissimos ipsa iusto labore laudantium magni obcaecati quia quidem quis, repudiandae similique soluta velit. Debitis explicabo, fugiat molestias nulla tempore unde.</a></li>
                <li class="subitem3"><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur dignissimos ipsa iusto labore laudantium magni obcaecati quia quidem quis, repudiandae similique soluta velit. Debitis explicabo, fugiat molestias nulla tempore unde.</a></li>
              </ul>
            </li>
          </ul>
        </div>

        <% unless @product.related.nil? %>
        <div class="latestproducts">
          <div class="product-one">
            <h3>Related Products</h3>
            <% @product.related.each do |related| %>
              <div class="col-xs-6 col-md-4 product-left p-left">
                <div class="product-main simpleCart_shelfItem">
                  <a href="<%= related.id %>" class="mask">
                    <%= image_tag related.image_url, alt: "", class: "img-responsive zoom-img"  if related.image_url%>
                  </a>
                  <div class="product-bottom">
                    <h3><a href="<%= related.id %>"><%= related.title %></a></h3>
                    <p>Explore Now</p>
                    <h4>
                      <a href="cart/add?id=<%= related.id %>" data-id="<%= related.id %>" class="item-add add-to-cart-link"><i></i></a>
                      <span class="item-price"><%= related.price %></span>
                      <% if related.old_price %>
                        <del><%= related.old_price %></del>
                      <% end %>
                    </h4>
                  </div>
                  <div class="srch"><span>-50%</span></div>
                </div>
              </div>
            <% end %>
            <div class="clearfix"></div>
          </div>
        </div>
      <% end %>

        <% if recent_products.any? %>
              <div class="latestproducts">
                <div class="product-one">
                  <h3>Resently Products</h3>
                  <% recent_products.each do |recently| %>
                    <div class="col-xs-6 col-sm-4 col-md-3 product-left p-left">
                      <div class="product-main simpleCart_shelfItem">
                        <a href="<%= recently.id %>" class="mask">
                          <%= image_tag(recently.image_url, alt: "", class: 'img-responsive zoom-img') if recently.image_url %> 
                        </a>
                        <div class="product-bottom">
                          <h3><a href="<%= recently.id %>"><%= recently.title %></a></h3>
                          <p>Explore Now</p>
                          <h4>
                            <a href="cart/add?id=<%= recently.id %>" data-id="<%= recently.id %>" class="item-add add-to-cart-link"><i></i></a>
                            <span class="item-price"><%= recently.price %></span>
                            <% if recently.old_price %>
                              <del><%= recently.old_price %></del>
                            <% end %>
                          </h4>
                        </div>
                        <div class="srch"><span>-50%</span></div>
                      </div>
                    </div>
                  <% end %>
                  <div class="clearfix"></div>
                </div>
              </div>
      <% end %>

      </div>

      <div class="col-md-3 single-right">
        <div class="w-sidebar">
          <section class="sky-form">
            <h4>Categories</h4>
            <div class="row1 scroll-pane">
              <% @categories.each do |category| %>
                <div class="col col-4">
                  <label class="checkbox"><input type="checkbox" name="checkbox"><i></i><%= link_to category.title, "/category/#{category.id}" %></label>
                </div>
              <% end %> 
            </div>
          </section>
          <% if @brands.present? %>
            <section class="sky-form">
              <h4>Brands</h4>
              <div class="row1 row2 scroll-pane">
                <% @brands.each do |brand|%>
                  <div class="col col-4">
                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i><%= link_to brand.title, category_path %></label>
                  </div>
                <% end %>
              </div>
            </section>
          <% end %>

          <section class="sky-form">
            <h4>Colour</h4>
            <ul class="w_nav2">
              <li><a href="#" class="color1"></a></li>
              <li><a href="#" class="color2"></a></li>
              <li><a href="#" class="color3"></a></li>
              <li><a href="#" class="color4"></a></li>
              <li><a href="#" class="color5"></a></li>
              <li><a href="#" class="color6"></a></li>
              <li><a href="#" class="color7"></a></li>
              <li><a href="#" class="color8"></a></li>
              <li><a href="#" class="color9"></a></li>
              <li><a href="#" class="color10"></a></li>
            </ul>
          </section>

          <section class="sky-form">
            <h4>discount</h4>
            <div class="row1 row2 scroll-pane">
              <div class="col col-4">
                <label class="radio"><input type="radio" name="radio" checked=""><i></i>60% and above</label>
                <label class="radio"><input type="radio" name="radio"><i></i>50% and above</label>
                <label class="radio"><input type="radio" name="radio"><i></i>40% and above</label>
              </div>
              <div class="col col-4">
                <label class="radio"><input type="radio" name="radio"><i></i>30% and above</label>
                <label class="radio"><input type="radio" name="radio"><i></i>20% and above</label>
                <label class="radio"><input type="radio" name="radio"><i></i>10% and above</label>
              </div>
            </div>
          </section>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>
<input type="hidden" value="<%= !current_user.nil? ? 88 : 99 %>" id="cart_access" />